# Generated by Django 5.1 on 2024-08-27 14:12

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Individual',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('password', models.CharField(max_length=128, verbose_name='password')),
                ('last_login', models.DateTimeField(blank=True, null=True, verbose_name='last login')),
                ('field_of_study', models.CharField(default='', max_length=32)),
                ('institution', models.CharField(default='', max_length=32)),
                ('nationality', models.CharField(default='', max_length=32)),
                ('first_name', models.CharField(default='', max_length=32)),
                ('last_name', models.CharField(default='', max_length=32)),
                ('username', models.CharField(default='', max_length=32)),
                ('email', models.EmailField(max_length=32)),
            ],
            options={
                'abstract': False,
            },
        ),
    ]
