# Generated by Django 5.1 on 2024-08-30 13:27

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('resources', '0005_keyword_papers_paper_eissn_paper_slug_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='keyword',
            name='papers',
        ),
        migrations.AlterField(
            model_name='paper',
            name='slug',
            field=models.SlugField(blank=True, default=''),
        ),
        migrations.AlterField(
            model_name='paper',
            name='upload_date',
            field=models.DateTimeField(default=datetime.datetime(2024, 8, 30, 14, 27, 50, 27054)),
        ),
    ]
