# Generated by Django 5.1 on 2024-08-30 13:31

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('resources', '0006_remove_keyword_papers_alter_paper_slug_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='paper',
            name='image',
            field=models.ImageField(blank=True, upload_to='paper_images'),
        ),
        migrations.AlterField(
            model_name='paper',
            name='title',
            field=models.CharField(default='', max_length=32),
        ),
        migrations.AlterField(
            model_name='paper',
            name='upload_date',
            field=models.DateTimeField(default=datetime.datetime(2024, 8, 30, 14, 31, 18, 750055)),
        ),
    ]
