# Generated by Django 5.1 on 2024-09-03 11:17

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('resources', '0007_alter_paper_image_alter_paper_title_and_more'),
    ]

    operations = [
        migrations.RenameField(
            model_name='paper',
            old_name='image',
            new_name='picture',
        ),
        migrations.AlterField(
            model_name='paper',
            name='upload_date',
            field=models.DateTimeField(default=datetime.datetime(2024, 9, 3, 12, 17, 36, 560705)),
        ),
    ]
