# Generated by Django 5.1 on 2024-09-03 11:19

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('resources', '0008_rename_image_paper_picture_alter_paper_upload_date'),
    ]

    operations = [
        migrations.AlterField(
            model_name='paper',
            name='picture',
            field=models.ImageField(upload_to='paper_images'),
        ),
        migrations.AlterField(
            model_name='paper',
            name='upload_date',
            field=models.DateTimeField(default=datetime.datetime(2024, 9, 3, 12, 19, 34, 802701)),
        ),
    ]
