# Generated by Django 5.1 on 2024-09-04 11:25

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('resources', '0009_alter_paper_picture_alter_paper_upload_date'),
    ]

    operations = [
        migrations.AlterField(
            model_name='paper',
            name='upload_date',
            field=models.DateTimeField(default=datetime.datetime(2024, 9, 4, 12, 25, 35, 100803)),
        ),
    ]
